env:
  global:
    - STORM_TEST_TIMEOUT_MS=13000
# Workaround for Travis CI issue 5227, which results in a buffer overflow
# caused by Java when running the build on OpenJDK.
# https://github.com/travis-ci/travis-ci/issues/5227
# https://docs.travis-ci.com/user/hostname
addons:
  hostname: travis-worker
script:
  - "./sbt test"
language: scala
scala:
   - 2.10.5

jdk:
  - openjdk7
  - oraclejdk7
