env:
  global:
    - STORM_TEST_TIMEOUT_MS=13000
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
script:
  - "./sbt test"
language: scala
scala:
   - 2.10.5

jdk:
  - openjdk7
  - oraclejdk7
